@startuml

class Clientes {
public String tarjetaIdentidad;
public String nombre;
public String apellido;
public List<String> sexo;
public Date fechaDeNacimiento;
public String email;
public String contraseña;
     
    
}

@enduml
